### ISSUE TITLE
golang dep complains about sirupsen/logrus

### ISSUE THREAD

**Issue by greenpau** [nuagenetworks/nuage-libnetwork#12]
I have the following constraint in `Gopkg.toml`.

```
[[constraint]]
  name = "github.com/nuagenetworks/nuage-libnetwork"
```

When I run `dep ensure`, it complaints that `nuage-libnetwork` uses upper-case `S` when referring to `logrus`, which the `logrus` itself is `github.com/sirupsen/logrus` (lowercase).

```
$ dep ensure
ensure Solve(): No versions of github.com/nuagenetworks/nuage-libnetwork met constraints:
	master: Could not introduce github.com/nuagenetworks/nuage-libnetwork@master due to a case-only variation: it depends on "github.com/Sirupsen/logrus", but "github.com/sirupsen/logrus" was already established as the case variant for that project root by depender (root)
```

The ask is to replace `Sirupsen` with `sirupsen` in this library.

See also from [logrus](https://github.com/sirupsen/logrus/blob/master/README.md):

> Everything using logrus will need to use the lower-case: github.com/sirupsen/logrus. Any package that isn't, should be changed.

**Comment by pdellaert** [comment]
It seems a lot of others seem to make the same mistake and it's a common issue. However, valid point and we'll see if addressing this in our own code, impacts anything (i doubt it). Thanks @greenpau

**Comment by tedli** [comment]
same problem

**Comment by andy-zhangtao** [comment]
Me too
master: Could not introduce github.com/docker/docker@master due to a case-only variation: it depends on "github.com/sirupsen/logrus", but "github.com/Sirupsen/logrus" was already established as the case variant for that project root by depender (root)

**Comment by pdellaert** [comment]
Thanks for the feedback all, we have a PR open which will solve this issue. We need to pull this through the proper QA procedure. cc @vareti
